### ISSUE TITLE
Transaction with "blockHash: null"

### ISSUE THREAD

**Issue by arturgontijo** [singnet/snet-cli#54]
Sometimes the transaction returns this receipt:

```
Proceed? (y/n): y
Submitting transaction...

    event_summaries:
    -   args:
            agent: '0xFD55Dc4276E31C7F2022997A2e8F296043C26D7b'
        event: AgentCreated
    receipt_summary:
        blockHash: null
        blockNumber: null
        cumulativeGasUsed: 2878039
        gasUsed: 1788285
        transactionHash: '0x22b8c631a1e9be622d6da1187538e940b983595f15ce966331f59e57ef6f9826'
```

Checking:
[identity.py:58-61](https://github.com/singnet/snet-cli/blob/master/snet_cli/identity.py#L58-L61)
[identity.py:86-89](https://github.com/singnet/snet-cli/blob/master/snet_cli/identity.py#L86-L89)
[identity.py:128-131](https://github.com/singnet/snet-cli/blob/master/snet_cli/identity.py#L128-L131)
[identity.py:179-182](https://github.com/singnet/snet-cli/blob/master/snet_cli/identity.py#L179-L182)
[identity.py:291-294](https://github.com/singnet/snet-cli/blob/master/snet_cli/identity.py#L291-L294)
I saw that it just wait for something in receipt but it doesn't check the content of the fields insite it.

Suggestion:
```
# Wait for transaction to be mined
receipt = dict()
while not receipt:
    time.sleep(1)
    receipt = self.w3.eth.getTransactionReceipt(txn_hash)
    if receipt and "blockHash" in receipt and receipt["blockHash"] is None:
        receipt = dict()
```
